### ISSUE TITLE
Missing list markers under some circumstances

### ISSUE THREAD

**Issue by SPiCaRiA** [Bluemoondragon07/obsidian-notation-2#6] opened 2023-03-29 01:07 UTC
For the souce markdown below:

```markdown
1. a
    1. b
        1. c
            1. d
    2. 
```

Under the editor mode it will be rendered as:
<img width="372" alt="Screen Shot 2023-03-28 at 18 05 10" src="https://user-images.githubusercontent.com/11176415/228400154-65bc9144-f332-424f-9270-abb54edd9152.png">

And we lose the level 2 markers in our list! I believe this is caused by the transparent marker color:

```css
 .has-list-bullet li li, .cm-list-2 {
  --list-marker-color: transparent; /* problematic line */
  --list-bullet-border: 1px solid var(--text-normal);
  --list-bullet-size: 0.25em;
 }
```

Not sure about the incentives behind so might need more context.

Thanks!

**Comment by Bluemoondragon07** [comment] 2023-03-29 02:03
Ah, I know what it is. That line was intended to only affect bulleted lists, so that the second level could be transparent with a black outline. I think it was because I was being too general with `.cm-list-2` that it extends over to numbered lists. A quick fix would be to remove `.cm-list-2`. A long-term solution would be to find the specific selector for bulleted lists in edit mode. 

I will be sure to make a fix this weekend. Thanks for notifying me of this issue!

**Comment by SPiCaRiA** [comment] 2023-03-29 02:29
> Ah, I know what it is. That line was intended to only affect bulleted lists, so that the second level could be transparent with a black outline. I think it was because I was being too general with `.cm-list-2` that it extends over to numbered lists. A quick fix would be to remove `.cm-list-2`. A long-term solution would be to find the specific selector for bulleted lists in edit mode.
> 
> I will be sure to make a fix this weekend. Thanks for notifying me of this issue!

Sure! Though I'm still not sure what notion behavior we are mimicing here :x I don't see a case where notion hides the second level bulleted list markers.

But yeah, take your time!

**Comment by Bluemoondragon07** [comment] 2023-04-05 21:01
Fixed in the latest version! Please update and enjoy!

**Closed as completed by Bluemoondragon07** 2023-04-05 21:01 UTC
